### ISSUE TITLE
1.20-rc1 dedicated server won't start.

### ISSUE THREAD

**Issue by Alasofia** [Enaium-FabricMC/OneKeyMiner#1]
Tried both the 1.20-pre7 release on Modrinth and the 1.20-rc1 release from the GitHub release here. 
Here's the log: https://pastebin.com/RSpuK47r

I've got a bunch of other mods installed, but the logs indicate this is the issue. I can list them if it'd be helpful.
Thanks!

**Comment by Alasofia** [comment]
It will boot with the most recent build for 1.20-pre6 though!
https://github.com/Enaium-FabricMC/OneKeyMiner/tree/1.20-pre6-1.4.0

**Comment by Enaium** [comment]
try 1.5.0?
