### ISSUE TITLE
(1.20-rc.1 1.5.0) OKM doesn't stop breaking Blocks.

### ISSUE THREAD

**Issue by Tursiops-G** [Enaium-FabricMC/OneKeyMiner#3]
Need a DEFAULT Block Break limit set on OKM when first installed. (Suggest either 8 or 16).
As it is, there is NO Default limit, which can be quite problematic for the uninitiated, resulting in severe griefing.
(IE: Devastating an Entire Forest with One Chop, or "Strip-Mining" an Entire Area)...

**Comment by Enaium** [comment]
Default is 300

**Comment by Tursiops-G** [comment]
The Default of 300 is Extremely Destructive in actual practise, IMO.
When used in a dense jungle environment, the resulting yield is Much Greater than just 300 Blocks. (It had cut over 10 stacks and counting, with no sign of stopping). I Had to exit/kill the world, Disable OKM and Restart in order to stop the griefing.

Also, If you mine a big enough ore vein, the result breaks the tool (even a new iron tool), and if you go into Spectator mode, you will find hidden pockets of dropped ore over a large area. (That is probably what overwhelms a Magnet mod).

I would strongly suggest a more conservative Default Limit, because of the potential for unintended destruction as it is currently.
Thank you for your consideration.

**Comment by arnokeesman** [comment]
video showcase of the before described behavior https://youtu.be/AJ28KGB6w7I

**Comment by Enaium** [comment]
> video showcase of the before described behavior https://youtu.be/AJ28KGB6w7I

Ok, I will fix this issue tomorrow.

**Comment by Enaium** [comment]
> video showcase of the before described behavior https://youtu.be/AJ28KGB6w7I

Can you send me your computer configuration?
Because my computer is faster.

**Comment by Enaium** [comment]
Fixed

**Comment by Enaium** [comment]
I've fixed the issue again, try to using 1.5.2 plz

**Comment by arnokeesman** [comment]
Niceee, this indeed does stop searching at non-matching blocks, the limit shouldn't even matter that much now

**Comment by Tursiops-G** [comment]
Good, No more Non-Contiguous block cutting/mining griefing.
I'd recommend keeping the Default limit at 64 anyway, just in case of encountering an Insanely Large (Contiguous) Ore Vein...
In that case, Just mining it 1 Full Stack at a time is quite reasonable, IMHO. :)
All Good.
